GAME_PACKAGES="
adventure.rpg.anime.game.vng.ys6
age.of.civilizations2.jakowski.lukasz
air.com.ubisoft.brawl.halla.platform.fighting.action.pvp
brownmonster.app.game.rushrally3
com.AlfaBravo.Combat
com.AlfaBravo.CombatMaster
com.CarXTech.highWay
com.CarXTech.street
com.ChillyRoom.DungeonShooter
com.EndlessClouds.Treeverse
com.EtherGaming.PocketRogues
com.Flanne.MinutesTillDawn.roguelike.shooting.gp
com.FosFenes.Sonolus
com.GameCoaster.ProtectDungeon
com.HoYoverse.Nap
com.HoYoverse.hkrpgoversea
com.HoYoverse.nap.gp
com.LanPiaoPiao.PlantsVsZombiesRH
com.MOBGames.PoppyMobileChap1
com.Nekootan.kfkjos.google
com.OxGames.Pluvia
com.PigeonGames.Phigros
com.PigeonGames.Rizline
com.ProjectMoon.LimbusCompany
com.Psyonix.RL2D
com.RickyG.DONTFORGET
com.RoamingStar.BlueArchive
com.RoosterGames.OffroadLeague
com.ShinyShoe.MonsterTrain.mtap
com.Shooter.ModernWarfront
com.Shooter.ModernWarship
com.Shooter.ModernWarships
com.Sunborn.SnqxExilium
com.Sunborn.SnqxExilium.Glo
com.TeamCherry.HollowKnight
com.TechTreeGames.TheTower
com.Vince.AlamobileFormula
com.WandaSoftware.TruckersofEurope3
com.Wispwood.ArrowQuest
com.YoStar.AetherGazer
com.YoStarEN.Arknights
com.YoStarEN.AzurLane
com.YoStarEN.HBR
com.YoStarEN.MahjongSoul
com.YoStarEN.StellaSora
com.YoStarJP.Arknights
com.YoStarJP.MajSoul
com.YostarJP.BlueArchive
com.ZeroCastleGameStudio.StrikeBusterPrototype
com.ZeroCastleGameStudioINTL.StrikeBusterPrototype
com.actgames.bbee
com.activision.callofduty.shooter
com.activision.callofduty.shooter.kr
com.activision.callofduty.warzone
com.albiononline
com.aligames.kuang.kybc
com.aligames.kuang.kybc.huawei
com.alightcreative.motion
com.and.games505.Terraria
com.and.games505.TerrariaPaid
com.android.test.uibench
com.andromeda.androbench2
com.arcelico.faces
com.archosaur.sea.dr.gp
com.asobimo.toramonline
com.autumn.skullgirls
com.axlebolt.standoff2
com.bairimeng.dmmdzz
com.bandainamcoent.dblegends_ww
com.bandainamcoent.idolmaster_gakuen
com.bandainamcoent.imas_millionlive_theaterdays
com.bandainamcoent.opbrww
com.bandainamcoent.sao
com.bandainamcoent.shinycolorsprism
com.bandainamcoent.tensuramrkww
com.bandainamcoent.ultimateninjastorm
com.bandainamcogames.dbzdokkanww
com.bf.sgs.hdexp.bd
com.bhvr.dbdmobile
com.bhvr.deadbydaylight
com.bilibili.azurlane
com.bilibili.deadcells.mobile
com.bilibili.fatego
com.bilibili.heaven
com.bilibili.priconne
com.bilibili.star.bili
com.bilibili.warmsnow
com.bilibiligame.heglgp
com.biligamekr.aggp
com.bingkolo.kleins.cn
com.blizzard.diablo.immortal
com.blizzard.wtcg.hearthstone
com.bluepoch.m.en.reverse1999
com.bscotch.crashlands2
com.bushiroad.d4dj
com.bushiroad.en.bangdreamgbp
com.bushiroad.lovelive.schoolidolfestival2
com.carxtech.drift
com.carxtech.drift2
com.carxtech.sr
com.carxtech.street
com.catsbit.vicecityonline
com.chillyroom.soulknightprequel
com.chucklefish.stardewvalley
com.citra.emu
com.cnvcs.xiangqi
com.codemasters.F1Mobile
com.coffeestain.goatsimulator3
com.com2us.starseedgl.android.google.global.normal
com.companyname.AM2RWrapper
com.criticalforceentertainment.criticalops
com.crunchyroll.princessconnectredive
com.cygames.umamusume
com.dena.a12026801
com.denachina.g13002010
com.denchi.vtubestudio
com.devsisters.ck
com.dfjz.moba
com.dgames.g15002002
com.digitalextremes.warframemobile
com.dishii.mm
com.dishii.soh
com.dois.greedgame
com.dolphinemu.dolphinemu
com.dragonli.projectsnow.lhm
com.drivezone.car.race.game
com.dts.freefireadv
com.dts.freefiremax
com.dts.freefireth
com.dts.freefireth.huawei
com.dwygame.crisisx.global
com.dxx.firenow
com.ea.game.nfs14_row
com.ea.game.pvz2_rfl
com.ea.game.pvz2_row
com.ea.game.pvzfree_row
com.ea.games.r3_row
com.ea.gp.apexlegendsmobilefps
com.ea.gp.easportsfc.mobile
com.ea.gp.fifamobile
com.ea.gp.nfsm
com.emulator.fpse64
com.epicgames.fortnite
com.epicgames.portal
com.epsxe.ePSXe
com.eyougame.msen
com.fajar.bussimulatorindonesia
com.fantablade.icey
com.farlightgames.farlight84.gp
com.farlightgames.igame.gp
com.feralinteractive.alienisolation_android
com.feralinteractive.companyofheroes_android
com.feralinteractive.gridas
com.feralinteractive.gridautosport_edition_android
com.feralinteractive.gridlegends_android
com.feralinteractive.hitmanabsolution_android
com.feralinteractive.tombraider_android
com.feralinteractive.totalwar_medieval2_android
com.feralinteractive.totalwarnapoleon_android
com.feralinteractive.tropico_android
com.feralinteractive.xcom2_android
com.firewick.p42.bilibili
com.firsttouchgames.dls7
com.fizzd.connectedworlds
com.focushome.mudrunnermobile
com.futuremark.dmandroid.application
com.gabama.monopostolite
com.gaijingames.wtm
com.gakpopuler.gamekecil
com.gameark.ggplay.lonsea
com.gamedevltd.wwh
com.gamehub.emulator
com.gameloft.android.ANMP.GloftA8HM
com.gameloft.android.ANMP.GloftA9HM
com.gameloft.android.ANMP.GloftMVHM
com.gameloft.android.SAMS.GloftA9SS
com.garena.codm.vn
com.garena.deltaforce
com.garena.game.alphaace
com.garena.game.codm
com.garena.game.df
com.garena.game.farlight84
com.garena.game.kgid
com.garena.game.kgtw
com.garena.game.kgvn
com.garena.game.lmjx
com.garena.game.nfsm
com.garena.game.undawn
com.gbits.funnyfighter.android.overseas
com.glu.left2survive
com.gravity.romg
com.gravity.roo.sea
com.gryphline.endfield.gp
com.gryphline.exastris.gp
com.guigugame.guigubahuang
com.guyou.deadstrike
com.h73.jhqyna
com.halo.windf.hero
com.haoplay.girlsfrontline
com.heavenburnsred
com.hermes.j1game
com.hermes.mk
com.herogame.gplay.magicminecraft.mmorpg
com.hg.cosmicshake
com.hg.lbw
com.hg.wreckfest
com.highbrowinteractive.truck.masters
com.hottapkgs.hotta
com.humblebundle.slaythespire
com.humo.yqqsqz.yw
com.hypergryph.arknights
com.hypergryph.exastris
com.idreamsky.klbqm
com.idreamsky.strinova
com.igg.android.doomsdaylastsurvivors
com.ignm.raspberrymash.jp
com.ilongyuan.implosion
com.infoldgames.infinitynikkien
com.innersloth.spacemafia
com.jacksparrow.jpmajiang
com.japan.datealive.gp
com.jarvigames.viceonline
com.je.supersus
com.jetsynthesys.realcricket20
com.jumpw.mobile300
com.kakaogames.eversoul
com.kakaogames.gdts
com.kakaogames.wdfp
com.kefirgames.lastdayonearth
com.kiloo.subwaysurf
com.kog.grandchaseglobal
com.komoe.kmumamusumegp
com.krafton.battlegrounds.india
com.kurogame.aki
com.kurogame.gplay.punishing.grayraven.en
com.kurogame.haru
com.kurogame.haru.bilibili
com.kurogame.haru.hero
com.kurogame.mingchao
com.kurogame.pgr.global
com.kurogame.wutheringwaves
com.kurogame.wutheringwaves.global
com.kurogame.wutheringwaves.gp
com.leiting.wf
com.lemcnsun.soultide.android
com.levelinfinite.arenabreakout
com.levelinfinite.deltaforce
com.levelinfinite.hotta.gp
com.levelinfinite.sgameGlobal
com.levelinfinite.sgameGlobal.midaspay
com.levelinfinite.undawn
com.lilithgame.hgame.gp
com.lilithgame.roc.gp
com.lilithgames.hgame.cn
com.linecorp.LGGRTHN
com.linegames.dz
com.linegames.exos
com.linegames.sl
com.linegames.smashlegends
com.linegames.ud
com.linegames.undecember
com.linegames.uwo
com.longe.allstarhmt
com.lrgame.dldl.sea
com.ludashi.benchmark
com.madfingergames.legends
com.madfingergames.shadowgunlegends
com.madout.big
com.maleo.bussimulatorid
com.manjuu.azurlane
com.miHoYo.GI.samsung
com.miHoYo.GenshinImpact
com.miHoYo.GenshinImpact.gp
com.miHoYo.HSoDv2JPOriginalEx
com.miHoYo.Nap
com.miHoYo.Yuanshen
com.miHoYo.ZenlessZoneZero
com.miHoYo.bh3
com.miHoYo.bh3.bilibili
com.miHoYo.bh3.mi
com.miHoYo.bh3.uc
com.miHoYo.bh3global
com.miHoYo.bh3oversea
com.miHoYo.bh3oversea_vn
com.miHoYo.bh3rdJP
com.miHoYo.enterprise.NGHSoD
com.miHoYo.hkrpg
com.miHoYo.hkrpg.gp
com.miHoYo.ys
com.miHoYo.zenless
com.minidragon.idlefantasy
com.miniworldgame.creata.vn
com.miraclegames.farlight84
com.mobile.legends
com.mobile.legends.gp
com.mobilechess.gp
com.mobilelegends.hwag
com.mobilelegends.mi
com.mobilelegends.taptest
com.mobiin.gp
com.modx.daluandou
com.mojang.hostilegg
com.mojang.minecraftpe
com.mojang.minecraftpe.patch
com.morizero.milthm
com.nanostudios.games.twenty.minutes
com.naturalmotion.customstreetracer2
com.ncsoft.lineagen
com.nebulajoy.act.dmcpoc.asia
com.nekki.shadowfight
com.nekki.shadowfight3
com.nekki.shadowfightarena
com.neowiz.game.idolypride.en
com.neowizgames.game.browndust2
com.netease.AVALON
com.netease.EVE
com.netease.aceracer
com.netease.allstar
com.netease.bloodstrike
com.netease.dbdena
com.netease.deltaforce
com.netease.dfjs
com.netease.dunkcd
com.netease.dunkcity
com.netease.dwrg
com.netease.eve
com.netease.eve.en
com.netease.frxyna
com.netease.g108na
com.netease.g78na.gb
com.netease.g93na
com.netease.h73hmt
com.netease.h75na
com.netease.hpwx.intl
com.netease.hpwx.intl.gp
com.netease.hyxd
com.netease.identityv
com.netease.idv
com.netease.idv.googleplay
com.netease.jddsaef
com.netease.ko
com.netease.l22
com.netease.lagrange
com.netease.lglr
com.netease.lztgglobal
com.netease.lztgglobal.gp
com.netease.ma100asia
com.netease.ma84
com.netease.moba
com.netease.mrzh
com.netease.newspike
com.netease.nshm
com.netease.nshmhmt
com.netease.onmyoji
com.netease.oncehuman
com.netease.party
com.netease.partyglobal
com.netease.partygp
com.netease.pes
com.netease.qrsj
com.netease.race
com.netease.racemaster
com.netease.racerna
com.netease.sky
com.netease.sky.gp
com.netease.soulofhunter
com.netease.tj
com.netease.tom
com.netease.wotb
com.netease.wyclx
com.netease.x19
com.netease.yhtj
com.netease.yysls
com.netease.yyslscn
com.netflix.NGP.GTAIIIDefinitiveEdition
com.netflix.NGP.GTASanAndreasDefinitiveEdition
com.netflix.NGP.GTAViceCityDefinitiveEdition
com.netmarble.skiagb
com.netmarble.sololv
com.netmarble.tog
com.nextwave.wcc3
com.nexon.bluearchive
com.nexon.dnfm
com.nexon.hit2
com.nexon.kartdrift
com.nexon.konosuba
com.nexon.maplem.global
com.nexon.mdnf
com.nexon.mod
com.nexon.tfd
com.nexon.traha
com.nexon.v4gb
com.ngame.allstar.eu
com.nianticlabs.monsterhunter
com.nianticproject.ingress
com.noctua.android.crazyones
com.noctuagames.android.ashechoes
com.olzhas.carparking.multyplayer
com.olzhas.carparking.multyplayer2
com.olzhass.carparking.multyplayer
com.oninou.FAPI
com.ovilex.cardrivingsimulator
com.ovilex.drivingschool2017
com.ovilex.drivingschoolsim
com.ovilex.farmingsim
com.ovilex.realdrivingsim
com.ovilex.streetracerevo
com.ovilex.taxi2020
com.ovilex.trucksimulatorevo
com.ovilex.trucksimworld
com.papegames.infinitynikki
com.papegames.lysk.en
com.papegames.nn4.en
com.pearlabyss.blackdesertm
com.pearlabyss.blackdesertm.gl
com.perfectworld.p5x
com.pinkcore.tkfm
com.plarium.raidlegends
com.play.rosea
com.playdigious.deadcells.mobile
com.playdigious.littlenightmares
com.playdigious.northgard
com.playmini.miniworld
com.pocketpair.palworld
com.popcap.pvz
com.primatelabs.geekbench6
com.proxima.dfm
com.proximabeta.dn2.global
com.proximabeta.mf.aceforce2
com.proximabeta.mf.liteuamo
com.proximabeta.mf.uamo
com.proximabeta.nikke
com.proximabeta.nikke.gp
com.proximabeta.towerofadventure
com.prpr.musedash
com.pubg
com.pubg.imobile
com.pubg.krmobile
com.pubg.newstate
com.pubg.vng
com.pwrd.hotta.laohu
com.pwrd.huanta
com.pwrd.nte
com.pwrd.opmwsea
com.pwrd.p5x
com.pwrd.persona5x.laohu
com.r2games.myhero.bilibili
com.rayark.cytus2
com.rayark.deemo2
com.rayark.deemoreborn
com.rayark.implosion
com.rayark.sdorica
com.rekoo.pubgm
com.republiqc.pubg
com.republiqc.pubgm
com.retroarch
com.rexhind.scars
com.rinzz.projectmuse
com.riotgames.league.teamfighttactics
com.riotgames.league.teamfighttacticstw
com.riotgames.league.teamfighttacticsvn
com.riotgames.league.wildrift
com.riotgames.league.wildrift.gp
com.riotgames.leagueoflegends
com.riotgames.teamfighttactics
com.riotgames.teamfighttactics.gp
com.riotgames.valorant
com.riotgames.valorant.global
com.riotgames.valorantmobile
com.roblox.client
com.roblox.client.vnggames
com.robtopx.geometryjump
com.rockstargames.bully
com.rockstargames.gta3
com.rockstargames.gta3.de
com.rockstargames.gtalcs
com.rockstargames.gtasa
com.rockstargames.gtasa.de
com.rockstargames.gtavc
com.rockstargames.gtavc.de
com.rsg.myheroesen
com.sandboxinteractive.albiononline
com.sandboxol.blockymods
com.seasun.jx3
com.seasun.snowbreak.google
com.sega.ColorfulStage.en
com.sega.pjsekai
com.sega.soniccd.classic
com.sgra.dragon
com.shangyoo.neon
com.shatteredpixel.shatteredpixeldungeon
com.shenlan.m.reverse1999
com.sidheinteractive.sif.gp
com.silverstarstudio.angellegion
com.sir.racing.limitation
com.smilegate.outerplane.google
com.smokoko.race
com.snapbreak.silt
com.sofunny.Sausage
com.soulgamechst.majsoul
com.spaceapegames.beatstar
com.sprduck.garena.vn
com.square_enix.android_googleplay.ffxvpe
com.squareenix.lis
com.starform.metalstorm
com.starry.oncehuman
com.stove.epic7.google
com.studiobside.CounterSide
com.studiowildcard.ark
com.studiowildcard.arkuse
com.studiowildcard.wardrumstudios.ark
com.studiowildcard.wardrumstudios.ark.ncr
com.sudachi.emulator
com.sugarfun.gp.sea.lzgwy
com.sunborn.gfl2
com.sunborn.girlsfrontline
com.sunborn.girlsfrontline.en
com.sunborn.net
com.sunborn.neuralcloud
com.sunborn.neuralcloud.en
com.superb.rhv
com.supercell.boombeach
com.supercell.brawlstars
com.supercell.brawlstars.gp
com.supercell.clashofclans
com.supercell.clashofclans.gp
com.supercell.clashroyale
com.supercell.clashroyale.gp
com.supercell.hayday
com.supercell.hayday.gp
com.supercell.squad
com.supercell.squad.gp
com.sy.dldlhsdj
com.sybogames.subway.surfers.game
com.t2ksports.nba2k20and
com.t2ksports.nba2k24myteam
com.tencent.KiHan
com.tencent.af
com.tencent.baiyeint
com.tencent.hhw
com.tencent.ig
com.tencent.iglite
com.tencent.jkchess
com.tencent.letsgo
com.tencent.lolm
com.tencent.mf.uam
com.tencent.msgame
com.tencent.nba2kx
com.tencent.nfsonline
com.tencent.ngame.chty
com.tencent.tmgp.WePop
com.tencent.tmgp.bh3
com.tencent.tmgp.cf
com.tencent.tmgp.cod
com.tencent.tmgp.codev
com.tencent.tmgp.df
com.tencent.tmgp.dfjs
com.tencent.tmgp.dfm
com.tencent.tmgp.dnf
com.tencent.tmgp.dwrg
com.tencent.tmgp.ffom
com.tencent.tmgp.gnyx
com.tencent.tmgp.kr.codm
com.tencent.tmgp.pubgm
com.tencent.tmgp.pubgmhd
com.tencent.tmgp.sgame
com.tencent.tmgp.sgamece
com.tencent.tmgp.speedmobile
com.tencent.tmgp.sskeus
com.tencent.tmgp.supercell.boombeach
com.tencent.tmgp.wuxia
com.tencent.tmgp.yys.zqb
com.tencent.toaa
com.tgc.sky.android
com.the10tons.dysmantle
com.tinybuildgames.helloneighbor
com.tipsworks.android.pascalswager
com.tipsworks.pascalswager
com.trampolinetales.lbal
com.tumuyan.ncnn.realsr
com.tungsten.fcl
com.ubisoft.assassinscreed.jade
com.ubisoft.division.resurgence
com.ubisoft.rainbow6.mobile.fps
com.ubisoft.rainbowsixmobile
com.ubisoft.rainbowsixmobile.r6.fps.pvp.shooter
com.unity.mmd
com.unknownworlds.subnautica
com.unknownworlds.subnauticabelowzero
com.uzuy.emu
com.valvesoftware.cswgsm
com.valvesoftware.source
com.vng.mlbbvn
com.vng.pubgm
com.vng.pubgmobile
com.vng.speedvn
com.vng.undawn
com.wb.goog.multi_versus
com.wb.goog.scribblenauts3
com.winlator
com.winlator.cmod
com.wondergames.warpath.gp
com.xd.TLglobal
com.xd.dxlzz.taptap
com.xd.muffin.gp.global
com.xd.rotaeno.googleplay
com.xd.rotaeno.tapcn
com.xd.ssrpgen
com.xd.terraria
com.xd.xdt
com.xd.xdtglobal.gp
com.xindong.torchlight
com.yinhan.hunter
com.yongshi.aethergazer
com.yongshi.tenojo
com.yoozoo.jgame.global
com.yoozoo.jgame.us
com.yostar.arknights
com.zlongame.mhmnz
com.ztgame.bob
com.ztgame.yyzy
com.zuuks.bus.simulator.ultimate
com.zuuks.truck.simulator.ultimate
com.zy.wqmt.cn
cyou.joiplay.joiplay
game.qualiarts.idolypride
gplay.punishing.grayraven
hg.toriteling.neetchan
id.rj01117883.liomeko
jp.co.bandainamcoent.BNEI0242
jp.co.craftegg.band
jp.co.cygames.princessconnectredive
jp.co.cygames.umamusume
jp.co.koeitecmo.ReslerianaGL
jp.garud.ssimulator
jp.goodsmile.touhoulostwordglobal_android
jp.konami.duellinks
jp.konami.masterduel
jp.konami.pesam
jp.pokemon.pokemonunite
lega.feisl.hhera
me.magnum.melonds.nightly
me.mugzone.emiria
me.pou.app
me.tigerhix.cytoid
minitech.miniworld
moe.low.arc
net.kdt.pojavlaunch
net.kdt.pojavlaunch.debug
net.kdt.pojavlaunch.firefly
net.wargaming.wot.blitz
net.wargaming.wows.blitz
nlch.game.Imouto
org.citra.emu
org.citron.citron_emu
org.dolphinemu.dolphinemu
org.flos.phira
org.godotengine.godot4
org.maxbytes.lfs
org.mm.jr
org.mupen64plusae.v3.alpha
org.mupen64plusae.v3.fzurita.pro
org.openttd.sdl
org.ppsspp.ppsspp
org.ppsspp.ppssppgold
org.sudachi.sudachi_emu.ea
org.uzuy.uzuy_emu.ea
org.vita3k.emulator
org.yuzu.yuzu_emu
pro.archiemeng.waifu2x
ro.alyn_sampmobile.game
ru.nsu.ccfit.zuev.osuplus
ru.unisamp_mobile.game
sh.ppy.osulazer
skyline.emu
skyline.purple
skynet.cputhrottlingtest
tw.sonet.allbw
tw.sonet.princessconnect
tw.txwy.and.arknights
uk.co.powdertoy.tpt
vng.games.revelation.mobile
www.townofmagic.com
xd.sce.promotion
xyz.aethersx2.android
"
